server:
  port: 2333

lavalink:
  server:
    password: ${LAVALINK_SERVER_PASSWORD:youshallnotpass}
    sources:
      youtube: false
      soundcloud: false
      bandcamp: false
      twitch: false
      vimeo: false
      http: true
      local: false
    bufferDurationMs: 400
    trackStuckThresholdMs: 30000
    youtubePlaylistLoadLimit: 101
    playerUpdateInterval: 5
    youtubeSearchEnabled: false
    soundcloudSearchEnabled: false
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0"
      repository: "https://maven.lavalink.dev/releases"
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.1"
      repository: "https://maven.lavalink.dev/releases"

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    remoteCipher:
      url: "http://yt-cipher:8001/"
    oauth:
      enabled: ${YOUTUBE_OAUTH_ENABLED:false}
      refreshToken: "${YOUTUBE_OAUTH_REFRESH_TOKEN:}"
      skipInitialization: ${YOUTUBE_OAUTH_SKIP_INITIALIZATION:false}
    clients:
      - TV
      - TVHTML5_SIMPLY
      - MWEB
      - WEBEMBEDDED
      - ANDROID_VR
      - WEB
      - MUSIC
    clientOptions:
      WEB:
        playback: false
      MUSIC:
        playback: false
  lavasrc:
    providers:
      - "ytsearch:\"%ISRC%\""
      - "ytsearch:%QUERY%"
    sources:
      spotify: true
      applemusic: false
      deezer: false
      yandexmusic: false
      flowerytts: false
    spotify:
      clientId: "${SPOTIFY_CLIENT_ID}"
      clientSecret: "${SPOTIFY_CLIENT_SECRET}"
      countryCode: "US"
      playlistLoadLimit: 101
      albumLoadLimit: 101

logging:
  level:
    root: INFO
    lavalink: INFO

